package UI;

import Comms.Communicator;
import MainFrame.MCU;
import MainFrame.Sorter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author Collin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel29 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        bin_1_Label = new javax.swing.JLabel();
        CB0 = new javax.swing.JComboBox<>();
        BC0 = new javax.swing.JLabel();
        EB0 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CB1 = new javax.swing.JComboBox<>();
        BC1 = new javax.swing.JLabel();
        EB1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CB2 = new javax.swing.JComboBox<>();
        BC2 = new javax.swing.JLabel();
        EB2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CB3 = new javax.swing.JComboBox<>();
        BC3 = new javax.swing.JLabel();
        EB3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        CB4 = new javax.swing.JComboBox<>();
        BC4 = new javax.swing.JLabel();
        EB4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        CB5 = new javax.swing.JComboBox<>();
        BC5 = new javax.swing.JLabel();
        EB5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        CB6 = new javax.swing.JComboBox<>();
        BC6 = new javax.swing.JLabel();
        EB6 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        CB7 = new javax.swing.JComboBox<>();
        BC7 = new javax.swing.JLabel();
        EB7 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        CB8 = new javax.swing.JComboBox<>();
        BC8 = new javax.swing.JLabel();
        EB8 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        CB9 = new javax.swing.JComboBox<>();
        BC9 = new javax.swing.JLabel();
        EB9 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        CB10 = new javax.swing.JComboBox<>();
        BC10 = new javax.swing.JLabel();
        EB10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        percentLabel = new javax.swing.JLabel();
        startStop = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jComboBox13 = new javax.swing.JComboBox<>();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        colorLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Sample = new javax.swing.JButton();
        chuteSelect = new javax.swing.JComboBox<>();
        ChuteNumber = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        algSelect = new javax.swing.JSlider();
        colorPercent = new javax.swing.JLabel();
        clearPercent = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel29.setText("jLabel29");

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel24.setText("Bin Number");

        jLabel25.setText("Contents");

        jLabel26.setText("Bead Count");

        jLabel27.setText("Empty");

        bin_1_Label.setText("Bin 0");

        CB0.setModel(new javax.swing.DefaultComboBoxModel<String>(Colors));
        CB0.setAutoscrolls(true);

        BC0.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BC0.setText("0");

        EB0.setText("Empty");
        EB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EB0ActionPerformed(evt);
            }
        });

        jLabel3.setText("Bin 1");

        CB1.setModel(new javax.swing.DefaultComboBoxModel<String>(Colors));
        CB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB1ActionPerformed(evt);
            }
        });

        BC1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BC1.setText("0");

        EB1.setText("Empty");
        EB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EB1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Bin 2");

        CB2.setModel(new javax.swing.DefaultComboBoxModel<String>(Colors));

        BC2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BC2.setText("0");

        EB2.setText("Empty");

        jLabel7.setText("Bin 3");

        CB3.setModel(new javax.swing.DefaultComboBoxModel<String>(Colors));

        BC3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BC3.setText("0");

        EB3.setText("Empty");

        jLabel9.setText("Bin 4");

        CB4.setModel(new javax.swing.DefaultComboBoxModel<String>(Colors));

        BC4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BC4.setText("0");

        EB4.setText("Empty");

        jLabel11.setText("Bin 5");

        CB5.setModel(new javax.swing.DefaultComboBoxModel<String>(Colors));

        BC5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BC5.setText("0");

        EB5.setText("Empty");

        jLabel14.setText("Bin 6");

        CB6.setModel(new javax.swing.DefaultComboBoxModel<String>(Colors));
        CB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB6ActionPerformed(evt);
            }
        });

        BC6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BC6.setText("0");

        EB6.setText("Empty");

        jLabel16.setText("Bin 7");

        CB7.setModel(new javax.swing.DefaultComboBoxModel<String>(Colors));

        BC7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BC7.setText("0");

        EB7.setText("Empty");

        jLabel18.setText("Bin 8");

        CB8.setModel(new javax.swing.DefaultComboBoxModel<String>(Colors));

        BC8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BC8.setText("0");

        EB8.setText("Empty");

        jLabel20.setText("Bin 9");

        CB9.setModel(new javax.swing.DefaultComboBoxModel<String>(Colors));

        BC9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BC9.setText("0");

        EB9.setText("Empty");

        jLabel22.setText("Bin 10");

        CB10.setModel(new javax.swing.DefaultComboBoxModel<String>(Colors));

        BC10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BC10.setText("0");

        EB10.setText("Empty");

        percentLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        percentLabel.setForeground(new java.awt.Color(0, 204, 0));
        percentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        percentLabel.setText("100 %");

        startStop.setText("Start/Stop");
        startStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startStopActionPerformed(evt);
            }
        });

        jButton13.setText("Go to Bin");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "500", "1000", "1500", "2000", "3000", "5000" }));
        jComboBox13.setSelectedIndex(1);

        jButton14.setText("Lock");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Chute Clockwise");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Chute Counter Clokwise");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        colorLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        colorLabel.setForeground(new java.awt.Color(0, 204, 0));
        colorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colorLabel.setText("Light Green");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perler - Regular" }));

        Sample.setText("Sample");
        Sample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SampleActionPerformed(evt);
            }
        });

        chuteSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        chuteSelect.setToolTipText("Selected bin.");
        chuteSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuteSelectActionPerformed(evt);
            }
        });

        ChuteNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ChuteNumber.setText("8");
        ChuteNumber.setToolTipText("Chute place for selected bin.  ");

        jLabel1.setText("Bin Place:");

        algSelect.setValue(70);
        algSelect.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                algSelectStateChanged(evt);
            }
        });
        algSelect.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                algSelectPropertyChange(evt);
            }
        });
        algSelect.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                algSelectVetoableChange(evt);
            }
        });

        colorPercent.setText("Color: 70%");

        clearPercent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clearPercent.setText("Clear: 30%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sample, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startStop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(percentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox13, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chuteSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChuteNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(algSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(colorPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearPercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(percentLabel)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startStop)
                .addGap(18, 18, 18)
                .addComponent(Sample)
                .addGap(18, 18, 18)
                .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(algSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorPercent)
                    .addComponent(clearPercent))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chuteSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChuteNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(jButton16)))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bin_1_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB0, 0, 114, Short.MAX_VALUE)
                    .addComponent(CB1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BC0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BC2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BC3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BC4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BC5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BC6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BC7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BC8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BC9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BC10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EB0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EB4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EB5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EB6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EB7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EB8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EB9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EB10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bin_1_Label)
                            .addComponent(CB0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BC0)
                            .addComponent(EB0))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BC1)
                            .addComponent(EB1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BC2)
                            .addComponent(EB2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(BC3)
                            .addComponent(EB3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(CB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BC4)
                            .addComponent(EB4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(CB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BC5)
                            .addComponent(EB5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(CB6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BC6)
                            .addComponent(EB6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(CB7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BC7)
                            .addComponent(EB7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(CB8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BC8)
                            .addComponent(EB8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(CB9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BC9)
                            .addComponent(EB9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(CB10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BC10)
                            .addComponent(EB10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int selected = chuteSelect.getSelectedIndex();
        mcu.lockChute(selected);
        if (selected < chuteSelect.getItemCount() - 1) {
            chuteSelect.setSelectedIndex(selected + 1);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void CB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB1ActionPerformed

    private void CB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB6ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        mcu.clk();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        mcu.cclk();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void EB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EB0ActionPerformed
        for (int i = 0; i < 11; i++) {
            try {
                mcu.toBin(i);
                Thread.sleep(3000);
            } catch (InterruptedException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_EB0ActionPerformed

    private void chuteSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuteSelectActionPerformed
        int index = chuteSelect.getSelectedIndex();
        ChuteNumber.setText(Integer.toString(mcu.getBinPlace(index)));
    }//GEN-LAST:event_chuteSelectActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int index = chuteSelect.getSelectedIndex();
        mcu.toBin(index);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void EB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EB1ActionPerformed

    }//GEN-LAST:event_EB1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        binNumbers[0] = CB0;
        binNumbers[1] = CB1;
        binNumbers[2] = CB2;
        binNumbers[3] = CB3;
        binNumbers[4] = CB4;
        binNumbers[5] = CB5;
        binNumbers[6] = CB6;
        binNumbers[7] = CB7;
        binNumbers[8] = CB8;
        binNumbers[9] = CB9;
        binNumbers[10] = CB10;

        binLabels[0] = BC0;
        binLabels[1] = BC1;
        binLabels[2] = BC2;
        binLabels[3] = BC3;
        binLabels[4] = BC4;
        binLabels[5] = BC5;
        binLabels[6] = BC6;
        binLabels[7] = BC7;
        binLabels[8] = BC8;
        binLabels[9] = BC9;
        binLabels[10] = BC10;
        
        sorterThread = new Thread(sorter);
    }//GEN-LAST:event_formWindowOpened

    private void startStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startStopActionPerformed
        if(sorter.isRunning()){
            sorter.stopThread();
        }else{
            sorterThread = new Thread(sorter);
            sorterThread.start();
        }
    }//GEN-LAST:event_startStopActionPerformed

    private void SampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SampleActionPerformed
        SampleFrame sf = new SampleFrame();
        sf.micro = mcu;
        sf.main();
    }//GEN-LAST:event_SampleActionPerformed

    private void algSelectPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_algSelectPropertyChange

    }//GEN-LAST:event_algSelectPropertyChange

    private void algSelectVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_algSelectVetoableChange

    }//GEN-LAST:event_algSelectVetoableChange

    private void algSelectStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_algSelectStateChanged
        System.out.println(algSelect.getValue());
        int percent = algSelect.getValue();
        colorPercent.setText("Color: " + percent + "%");
        clearPercent.setText("Clear: " + (100 - percent) + "%");
        sorter.setAlg(percent);
    }//GEN-LAST:event_algSelectStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        mcu.mcu.disconnect();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public void recordBead(int index, float percent) {
        int binNumber = checkChute(index);
        binBeadCount[binNumber] += 1;
        binLabels[binNumber].setText(Integer.toString(binBeadCount[binNumber]));
        mcu.setBead(binNumber);
        percentLabel.setText(percent + " %");
        colorLabel.setText(Colors[index + 1]);
        //if this is a black or grey bead.  This is where we check to see if there too many black beads. 
        //if there are too many, (25 in a row) then we will stop the sort because we assume that the hopper is empty.  
        if(index == 25 | index == 30){  
            blackBeadCount++;
            if(blackBeadCount >= 25){
                sorter.stopThread();
            }
        }else{
            blackBeadCount = 0;
        }
    }

    private int checkChute(int index) {
        int chute = 0;
        System.out.println(index);
        index++;
        for (int i = 0; i < 11; i++) {
            if (binNumbers[i].getSelectedIndex() == index) {
                System.out.println(i);
                return i;
            }
        }
        index = 0;
        for (int i = 0; i < 11; i++) {
            if (binNumbers[i].getSelectedIndex() == 0) {
                return i;
            }
        }
        return -1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BC0;
    private javax.swing.JLabel BC1;
    private javax.swing.JLabel BC10;
    private javax.swing.JLabel BC2;
    private javax.swing.JLabel BC3;
    private javax.swing.JLabel BC4;
    private javax.swing.JLabel BC5;
    private javax.swing.JLabel BC6;
    private javax.swing.JLabel BC7;
    private javax.swing.JLabel BC8;
    private javax.swing.JLabel BC9;
    private javax.swing.JComboBox<String> CB0;
    private javax.swing.JComboBox<String> CB1;
    private javax.swing.JComboBox<String> CB10;
    private javax.swing.JComboBox<String> CB2;
    private javax.swing.JComboBox<String> CB3;
    private javax.swing.JComboBox<String> CB4;
    private javax.swing.JComboBox<String> CB5;
    private javax.swing.JComboBox<String> CB6;
    private javax.swing.JComboBox<String> CB7;
    private javax.swing.JComboBox<String> CB8;
    private javax.swing.JComboBox<String> CB9;
    private javax.swing.JLabel ChuteNumber;
    private javax.swing.JButton EB0;
    private javax.swing.JButton EB1;
    private javax.swing.JButton EB10;
    private javax.swing.JButton EB2;
    private javax.swing.JButton EB3;
    private javax.swing.JButton EB4;
    private javax.swing.JButton EB5;
    private javax.swing.JButton EB6;
    private javax.swing.JButton EB7;
    private javax.swing.JButton EB8;
    private javax.swing.JButton EB9;
    private javax.swing.JButton Sample;
    private javax.swing.JSlider algSelect;
    private javax.swing.JLabel bin_1_Label;
    private javax.swing.JComboBox<String> chuteSelect;
    private javax.swing.JLabel clearPercent;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JLabel colorPercent;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel percentLabel;
    private javax.swing.JButton startStop;
    // End of variables declaration//GEN-END:variables

    //array organizers for ease of use.  These components are the same as above.  
    private javax.swing.JComboBox[] binNumbers = new JComboBox[11];
    private javax.swing.JLabel[] binLabels = new JLabel[11];
    private int[] binBeadCount = new int[11];
    private javax.swing.JLabel[] beadCount = {BC0, BC1, BC2, BC3, BC4, BC5, BC6, BC7, BC8, BC9, BC10};
    private javax.swing.JButton[] emptyBin = {EB0, EB1, EB2, EB3, EB4, EB5, EB6, EB7, EB8, EB9, EB10};
    private int[] binColors = new int[11];
    private int blackBeadCount = 0;

    public static MCU mcu;

    public static String[] Colors = {
        "Default",
        "Lavender",
        "Plumb",
        "Pink",
        "Magenta",
        "Kiwi Lime",
        "Dark Green",
        "Clear Green",
        "Parrot Gereen",
        "Dark Blue",
        "Pastel Blue",
        "Light Blue",
        "Toothpaste",
        "Light Green",
        "Yellow",
        "Clear Yellow",
        "Cheddar",
        "Butterscotch",
        "Sand",
        "Peach",
        "Clear Pink",
        "Blush",
        "Hot Pink",
        "Dark Brown",
        "Light Brown",
        "Black",
        "Clear",
        "Red",
        "Clear Orange",
        "White",
        "Grey",};

    Sorter sorter = new Sorter(this, mcu);
    Thread sorterThread;
}
